### ISSUE TITLE
Error "No 3D video card found"

### ISSUE THREAD

**Issue by DiegoFLA** [jglim/gunbound-launcher#4]
I am getting this error when trying to run Launcher.exe:

![image](https://user-images.githubusercontent.com/72291778/106363617-56146f00-6308-11eb-8893-d95d4b9cb9ec.png)

Tried Windows 7 compatibily mode, but without sucess

**Comment by jglim** [comment]
The error message should have been created by the game client itself, which is independent of the launcher. (The launcher has no error messages involving 3D issues).

In this case, it is probably a game/OS compatibility issue and there is nothing that the launcher can do, since it is working as intended.
